.\" Manpage for mod-pack.
.\" Post an issue on https://github.com/snailcreature/mod-pack to correct errors or typos.
.TH man 1 "25 February 2023" "1.0" "mod-pack man page"
.SH NAME
mod-pack \- create global modpacks and serverpacks for CurseForge modpacks
.SH SYNOPSIS
mod-pack init \- Create the required files

mod-pack update \- Update mod list

mod-pack build \- Build the modpack files
.SH DESCRIPTION
mod-pack allows modpack creators to generate both a global modpack and a serverpack for their creations. It outputs directories for both global- and serverpacks, along with their compressed .zip files for easy upload to the CurseForge platform.
.SH OPTIONS
--version \- Show version number

--help \- Show help
.SH SEE ALSO
N/A
.SH BUGS
No known bugs.
.SH AUTHOR
Sam Drage (https://www.snail.codes)